# Generated by Django 2.1.3 on 2018-11-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='', max_length=128)),
                ('cards', models.CharField(default='', max_length=1024)),
                ('players', models.IntegerField()),
                ('winner', models.IntegerField()),
                ('count_cards_to_win', models.IntegerField()),
            ],
        ),
    ]
